version: "3"
services:
  
  app:
    build: .
    depends_on:
      - postgres
    environment:
      PORT: 3000
    ports:
      - "3000:3000"
      - "9229:9229"
    command: npm run start:dev
    
    volumes:
      - .:/app/
#      - /app/node_modules

  postgres:
    image: postgres:10.4
    ports:
      - "5432:5432"
    expose:
      - 5432
    environment:
      POSTGRES_PASSWORD: postgres